### ISSUE TITLE
LaTeX Templates not copied at installation

### ISSUE THREAD

**Issue by orestesmas** [orestesmas/pycirkuit#3]
Latex templates, necessary to process source file, are not copied from their location in source code to the destination directory when doing a ```pip install ...```

The code should search for templates also in this directory

**Comment by aniolm9** [comment]
The templates are copied when installing, but they are not loaded.

Creating the environment in `/opt/pycirkuit` the templates are located in `/opt/pycirkuit/venv/lib/python3.5/site-packages/pycirkuit/templates` but they still have to be manually loaded. I think the bug should be reopened.
