### ISSUE TITLE
Circuit schematic window doesn't resize when it is located in a side

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#36]
**Describe the bug**
The window containing the circuit schematic can be moved in 4 different positions: top, bottom, left and right. If this window is in one of the sides (right or left) and you use Ctrl+Mouse to zoom the window does not resize, but in the top or bottom it does.

**To Reproduce**
1. Open PyCirkuit.
2. Open a ckt example.
3. Move the window to the right or left.
4. Zoom.
5. See error

**Expected behavior**
The window should resize as it does when it is located at top or bottom.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux v9.8.
 - Python 3.5.3.
 - PyCirkuit develop branch.
 - `pip3 install --upgrade https://github.com/orestesmas/pycirkuit/archive/develop.zip`
 - PyCirkuit is installed inside a venv.

**Comment by orestesmas** [comment]
Closed by a5ff0756
