### ISSUE TITLE
[BUG] PyCirkuit ignores extension in the permission denied save box

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#58]
**Describe the bug**
PyCirkuit ignores extension in the permission denied save box.

**To Reproduce**
1. Open PyCirkuit.
2. Go to "File/Open...".
3. Open a file in a protected directory.
4. Click on "Export".
5. A save box will appear asking for a file name and a file type.
6. See how the file type field is ignored.

**Expected behavior**
Only the set format should be saved, but it tries to save all the formats in settings ignoring the file type. It will also open a dialog box for every format in settings ignoring the previous dialog.

**Desktop (please complete the following information):**
 - OS: Debian Testing/Bullseye
 - Python 3.7.5
 - PyCirkuit 0.5.0-2 (Debian package)

**Comment by orestesmas** [comment]
Ok. The dialog that appears should ask only for an alternative dir where to place the exported files, without thw "file type" list box.

**Comment by orestesmas** [comment]
Closed by 7e26ff4b
