### ISSUE TITLE
Weird path for circuit macros

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#9]
When running Pycirkuit for the first time, circuit macros are downloaded in `~/.local/share/UPC/pycirkuit/circuit_macros`. I think it would be better to change it to: `~/.local/share/pycirkuit/circuit_macros` as it is a more usual path.

**Comment by orestesmas** [comment]
In fact this path isn't entirely my choice, as is chosen by Qt libraries when you ask for a writable location where to put the app's data:
```
QtCore.QStandardPaths.writableLocation(QtCore.QStandardPaths.AppDataLocation)
```

Previously you have to define the organization and application name, which the former code uses to construct a unique writable location for each application:

```
QCoreApplication.setOrganizationName("UPC")
QCoreApplication.setApplicationName("pycirkuit")
```
All this is to avoid name clashing, obviously, but leads to the "weird" location you talked about.
I too found this path weird the first time i saw it. Now I'm used to it. But I'll consider to remove the "OrganizationName" part to obtain the path you propose.

**Comment by aniolm9** [comment]
The pull request #11 I opened does exactly this, remove the OrganizationName setting in main.py.
